name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials (use your GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # 3. Sync only the frontend folder to your S3 bucket
      #    Make sure your frontend files (index.html, CSS, JS) live in ./frontend
      - name: Upload website to S3
        run: |
          aws s3 sync ./frontend s3://cormacsawsbucket \
            --delete \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      # 4. Invalidate CloudFront cache (forces refresh of your live site)
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1IB3WFY18A411 \
            --paths "/*"
